management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    discover-composite:
      enabled: false
    ping:
      enabled: false
    refresh:
      enabled: false
    diskspace:
      enabled: false
    mongo:
      enabled: false
    kafka:
      enabled: true  # Ensures Kafka health is checked

logging:
  level:
    com.lantanagroup.link: debug

server:
  port: 5135

telemetry:
  exporterEndpoint: http://localhost:55690

loki:
  enabled: true
  url: http://localhost:3100
  app: link-cloud

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:

  cloud:
    discovery:
      enabled: false

  application:
    name: measureeval

  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}?serverSelectionTimeoutMS=4000
      database: ${spring.application.name}

  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ${spring.application.name}

    producer:
      client-id: ${spring.application.name}

    retry:
      maxAttempts: 3
      retry-backoff-ms: 3000

link:
  reportability-predicate: com.lantanagroup.link.measureeval.reportability.IsInInitialPopulation
  cql-debug: false

secret-management:
  key-vault-uri: ''

authentication:
  anonymous: false
  authority: 'https://localhost:7004'
