trigger:
  paths:
    include:
      - DotNet/Shared/*

pr:
  paths:
    include:
      - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/Shared.csproj'
  testProject: 'DotNet/SharedTests/SharedTests.csproj'
  serviceName: 'Shared'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
      arguments: --collect "Code coverage"
    displayName: 'Run Tests'